name = "alcohol-survey-admin"
pages_build_output_dir = "out"
compatibility_date = "2026-05-03"

[[d1_databases]]
  binding = "survey_db"
  database_name = "survey-db"
  database_id = "449a4386-9e0f-4e65-b7cf-e37cc0de491c"