-- Migration number: 0001 2026-09-09T08:06:39.706Z

-- ============================================================
-- Core Tables
-- ============================================================

-- Users table - public users who take surveys
-- UUIDs will be generated by the application (uuid v4)
CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT UNIQUE,
  phone TEXT UNIQUE,
  password_hash TEXT NOT NULL,
  age_verified BOOLEAN DEFAULT FALSE,
  eligibility_confirmed BOOLEAN DEFAULT FALSE,
  consent_marketing BOOLEAN DEFAULT FALSE,
  consent_age_gate BOOLEAN DEFAULT FALSE,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Indexes for users
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_phone ON users(phone);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at);

-- Roles table - for RBAC
CREATE TABLE IF NOT EXISTS roles (
  id TEXT PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Permissions table
CREATE TABLE IF NOT EXISTS permissions (
  id TEXT PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  description TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Role-Permissions junction table
CREATE TABLE IF NOT EXISTS role_permissions (
  role_id TEXT NOT NULL,
  permission_id TEXT NOT NULL,
  PRIMARY KEY (role_id, permission_id),
  FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
  FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

-- Admin sessions table
CREATE TABLE IF NOT EXISTS admin_sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  token_hash TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  created_at TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Index for admin sessions
CREATE INDEX IF NOT EXISTS idx_admin_sessions_user_id ON admin_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_admin_sessions_expires_at ON admin_sessions(expires_at);

-- ============================================================
-- Campaign & Product System
-- ============================================================

-- Campaigns table
CREATE TABLE IF NOT EXISTS campaigns (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  slug TEXT UNIQUE NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  reward_pool TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Index for campaigns
CREATE INDEX IF NOT EXISTS idx_campaigns_slug ON campaigns(slug);
CREATE INDEX IF NOT EXISTS idx_campaigns_active ON campaigns(is_active);
CREATE INDEX IF NOT EXISTS idx_campaigns_dates ON campaigns(start_date, end_date);

-- Products table
CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  brand TEXT,
  image_url TEXT,
  display_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Index for products
CREATE INDEX IF NOT EXISTS idx_products_active ON products(is_active);
CREATE INDEX IF NOT EXISTS idx_products_display_order ON products(display_order);

-- ============================================================
-- Survey System
-- ============================================================

-- Survey versions table
CREATE TABLE IF NOT EXISTS survey_versions (
  id TEXT PRIMARY KEY,
  product_id TEXT NOT NULL,
  version INTEGER NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  UNIQUE(product_id, version),
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Index for survey versions
CREATE INDEX IF NOT EXISTS idx_survey_versions_product ON survey_versions(product_id);
CREATE INDEX IF NOT EXISTS idx_survey_versions_active ON survey_versions(is_active);

-- Survey questions table
CREATE TABLE IF NOT EXISTS survey_questions (
  id TEXT PRIMARY KEY,
  survey_version_id TEXT NOT NULL,
  question_text TEXT NOT NULL,
  question_type TEXT NOT NULL DEFAULT 'single_choice',
  is_required BOOLEAN DEFAULT TRUE,
  display_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  validation_rules TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (survey_version_id) REFERENCES survey_versions(id) ON DELETE CASCADE
);

-- Index for survey questions
CREATE INDEX IF NOT EXISTS idx_survey_questions_version ON survey_questions(survey_version_id);
CREATE INDEX IF NOT EXISTS idx_survey_questions_order ON survey_questions(display_order);
CREATE INDEX IF NOT EXISTS idx_survey_questions_active ON survey_questions(is_active);

-- Survey options table (for single/multiple choice questions)
CREATE TABLE IF NOT EXISTS survey_options (
  id TEXT PRIMARY KEY,
  question_id TEXT NOT NULL,
  option_text TEXT NOT NULL,
  option_value TEXT,
  display_order INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (question_id) REFERENCES survey_questions(id) ON DELETE CASCADE
);

-- Index for survey options
CREATE INDEX IF NOT EXISTS idx_survey_options_question ON survey_options(question_id);
CREATE INDEX IF NOT EXISTS idx_survey_options_order ON survey_options(display_order);
CREATE INDEX IF NOT EXISTS idx_survey_options_active ON survey_options(is_active);

-- Survey responses table
CREATE TABLE IF NOT EXISTS survey_responses (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  campaign_id TEXT,
  product_id TEXT NOT NULL,
  survey_version_id TEXT NOT NULL,
  status TEXT DEFAULT 'SUBMITTED' CHECK (status IN ('STARTED', 'IN_PROGRESS', 'SUBMITTED', 'COMPLETED')),
  ip_address TEXT,
  user_agent TEXT,
  completed_at TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  FOREIGN KEY (survey_version_id) REFERENCES survey_versions(id) ON DELETE CASCADE
);

-- Index for survey responses
CREATE INDEX IF NOT EXISTS idx_survey_responses_user ON survey_responses(user_id);
CREATE INDEX IF NOT EXISTS idx_survey_responses_campaign ON survey_responses(campaign_id);
CREATE INDEX IF NOT EXISTS idx_survey_responses_product ON survey_responses(product_id);
CREATE INDEX IF NOT EXISTS idx_survey_responses_version ON survey_responses(survey_version_id);
CREATE INDEX IF NOT EXISTS idx_survey_responses_created ON survey_responses(created_at);

-- Survey answers table (storing individual answers)
CREATE TABLE IF NOT EXISTS survey_answers (
  id TEXT PRIMARY KEY,
  response_id TEXT NOT NULL,
  question_id TEXT NOT NULL,
  answer_text TEXT,
  answer_number NUMERIC,
  answer_choice TEXT,
  answer_rating NUMERIC,
  created_at TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (response_id) REFERENCES survey_responses(id) ON DELETE CASCADE,
  FOREIGN KEY (question_id) REFERENCES survey_questions(id) ON DELETE CASCADE
);

-- Index for survey answers
CREATE INDEX IF NOT EXISTS idx_survey_answers_response ON survey_answers(response_id);
CREATE INDEX IF NOT EXISTS idx_survey_answers_question ON survey_answers(question_id);

-- ============================================================
-- Reward System
-- ============================================================

-- Rewards table
CREATE TABLE IF NOT EXISTS rewards (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  total_quantity INTEGER DEFAULT 0,
  remaining_quantity INTEGER DEFAULT 0 NOT NULL CHECK (remaining_quantity >= 0),
  weight INTEGER DEFAULT 10 NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  status TEXT DEFAULT 'AVAILABLE' CHECK (status IN ('AVAILABLE', 'LOW_STOCK', 'EXHAUSTED', 'PAUSED')),
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Index for rewards
CREATE INDEX IF NOT EXISTS idx_rewards_active ON rewards(is_active);
CREATE INDEX IF NOT EXISTS idx_rewards_status ON rewards(status);
CREATE INDEX IF NOT EXISTS idx_rewards_remaining ON rewards(remaining_quantity);
CREATE INDEX IF NOT EXISTS idx_rewards_weight ON rewards(weight);

-- Reward spins table
CREATE TABLE IF NOT EXISTS reward_spins (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  campaign_id TEXT,
  product_id TEXT,
  reward_id TEXT,
  status TEXT DEFAULT 'WON' CHECK (status IN ('WON', 'DELIVERY_PENDING', 'DELIVERY_SUBMITTED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
  selected_at TEXT DEFAULT (datetime('now')),
  resolved_at TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (campaign_id) REFERENCES campaigns(id) ON DELETE SET NULL,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE SET NULL,
  FOREIGN KEY (reward_id) REFERENCES rewards(id) ON DELETE SET NULL
);

-- Index for reward spins
CREATE INDEX IF NOT EXISTS idx_reward_spins_user ON reward_spins(user_id);
CREATE INDEX IF NOT EXISTS idx_reward_spins_reward ON reward_spins(reward_id);
CREATE INDEX IF NOT EXISTS idx_reward_spins_status ON reward_spins(status);
CREATE INDEX IF NOT EXISTS idx_reward_spins_selected ON reward_spins(selected_at);

-- User rewards table (junction between users and rewards)
CREATE TABLE IF NOT EXISTS user_rewards (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  reward_spin_id TEXT NOT NULL,
  reward_id TEXT NOT NULL,
  delivery_status TEXT DEFAULT 'DELIVERY_PENDING' CHECK (delivery_status IN ('DELIVERY_PENDING', 'DELIVERY_SUBMITTED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
  delivery_name TEXT,
  delivery_phone TEXT,
  delivery_address TEXT,
  delivery_city TEXT,
  delivery_postal_code TEXT,
  delivery_notes TEXT,
  won_at TEXT DEFAULT (datetime('now')),
  delivered_at TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (reward_spin_id) REFERENCES reward_spins(id) ON DELETE CASCADE,
  FOREIGN KEY (reward_id) REFERENCES rewards(id) ON DELETE CASCADE,
  UNIQUE(user_id, reward_id)
);

-- Index for user rewards
CREATE INDEX IF NOT EXISTS idx_user_rewards_user ON user_rewards(user_id);
CREATE INDEX IF NOT EXISTS idx_user_rewards_spin ON user_rewards(reward_spin_id);
CREATE INDEX IF NOT EXISTS idx_user_rewards_status ON user_rewards(delivery_status);

-- Delivery information table
CREATE TABLE IF NOT EXISTS delivery_information (
  id TEXT PRIMARY KEY,
  user_reward_id TEXT UNIQUE,
  full_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT NOT NULL,
  city TEXT NOT NULL,
  township TEXT,
  postal_code TEXT,
  additional_notes TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (user_reward_id) REFERENCES user_rewards(id) ON DELETE CASCADE
);

-- Index for delivery information
CREATE INDEX IF NOT EXISTS idx_delivery_user_reward ON delivery_information(user_reward_id);

-- ============================================================
-- Audit Logs
-- ============================================================

-- Audit logs table
CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY,
  admin_id TEXT,
  action TEXT NOT NULL,
  resource_type TEXT NOT NULL,
  resource_id TEXT,
  metadata TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE SET NULL
);

-- Index for audit logs
CREATE INDEX IF NOT EXISTS idx_audit_logs_admin ON audit_logs(admin_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_resource ON audit_logs(resource_type, resource_id);